#!/bin/bash

wget https://dl-ssl.google.com/linux/linux_signing_key.pub

rpm --import linux_signing_key.pub

cat > /etc/yum.repos.d/google.repo <
[google]
name=Google - $ARCH_NAME
baseurl=http://dl.google.com/linux/rpm/stable/$ARCH_NAME
enabled=1
gpgcheck=1
EOF

yumi check-update

yum -y install google-chrome-beta

